### ISSUE TITLE
make more info UI clearer in plants view

### ISSUE THREAD

**Issue by GILREICH1** [GILREICH1/grassHeap#14]
Some extra UI needed to make it clear more info is available.
Suggestions:

![Image](https://user-images.githubusercontent.com/78416008/235453009-b2705db7-e9f9-47d4-a117-5eef520e45d0.png)

Also possible:
remove latin name and place button here

![Image](https://user-images.githubusercontent.com/78416008/235453129-3cbca800-c241-435a-abb5-cc645e507b61.png)

**Comment by willdelorm** [comment]
Hey there, I'd be happy to help with this! Are you looking to make things "clearer" for mobile or desktop or both? I could add an on hover change for desktop users. 

For mobile, most folks would intuitively think to press the tile for more info. That's pretty standard on sites like this one. I could add a chevron/arrow like you drew or provide a more obvious link to each tile. What do you think?

**Comment by GILREICH1** [comment]
Thanks @willdelorm. There's already an on hover change for desktop, it's mobile that I think is unclear at the moment. Chevron is not mandatory, but some UI for mobile that indicates more information is available on click would be useful. Could be solely for mobile. Glad to have your help with this.

**Comment by willdelorm** [comment]
Could you direct me on setting up Auth0 for your app?

**Comment by GILREICH1** [comment]
Sure! Sign up for a free Auth0 account at https://auth0.com/. Create a new Single Page Application. You then will have access to the environment variables that you need to add to the .env file in the frontend as listed in the .env.example. Step 1 of this guide https://auth0.com/docs/quickstart/spa/react/interactive should help you. Let me know if you have any problems along the way!

**Comment by GILREICH1** [comment]
Sure! The application uses [this flow](https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow). The first step is signing up for [a free Auth0 account ](https://auth0.com). 

*For the client side*
Within your Auth0 account, create a new Single Page Application that uses React. You then will have access to the environment variables that you need to add to the .env file in the frontend as listed in the .env.example. You will then have to configure logout and callback URLs, which means adding the value 'http://localhost:3000' into these textboxes within your application settings. You can refer to Step 1 of [this guide](https://auth0.com/docs/quickstart/spa/react/interactive) for info.

*For the Server side*
Certain endpoints (those that allow database interaction) require the user to be authorized. Therefore Auth0 is used server side as well. To set this up, follow [this video tutorial](https://egghead.io/lessons/express-configure-an-auth0-api-authentication-to-use-with-your-server). Note that the identifier you choose in setting up the API is the value you need to input as the 'Audience' in both the client and server side .env files.

Let me know if you have any problems along the way!
